### ISSUE TITLE
при пуске сервера сразу показать браузер с текущей страницей

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_html_live_preview#15]
чтобы не надо было делать правку.

**Comment by ahreenah** [comment]
не очень понатно как зааставить питон запускать нормальный браузер не зная путь его установки

**Comment by Alexey-T** [comment]
https://pymotw.com/2/webbrowser/

**Comment by ahreenah** [comment]
на винде пускает эксплорер и ничего больше, для остальных надо прописать путь

**Comment by Alexey-T** [comment]
https://pymotw.com/2/webbrowser/ не работает? первый раз слышу

**Comment by ahreenah** [comment]
работает но открывает эксплорер

**Comment by Alexey-T** [comment]
там описано как пускать другие- 
b = get('firefox')
...

**Comment by ahreenah** [comment]
![image](https://user-images.githubusercontent.com/38169798/58176964-1cbedb80-7cac-11e9-9470-8cfd25c7d624.png)

**Comment by Alexey-T** [comment]
>>> w.get('firefox')
<webbrowser.Mozilla object at 0x7ffbf54bc4a8>

**Comment by Alexey-T** [comment]
'chrome' тоже должен найти. если нет- можешь пускать просто как Popen

**Comment by ahreenah** [comment]
у меня не находит, я же скриншот скинул

**Comment by ahreenah** [comment]
![image](https://user-images.githubusercontent.com/38169798/58177534-3ca2cf00-7cad-11e9-9a2a-8ce83e09cd83.png)

**Comment by Alexey-T** [comment]
хром портабельный?
надо дать выбор из 'firefox', 'chrome', 'windows-default'.
https://docs.python.org/3/library/webbrowser.html#webbrowser.register

и еще тогда в конфиг-файле дать прописать путь к .exe.

**Comment by ahreenah** [comment]
тогда в конфиге создаем два поля - имя браузера и путь к нему?

**Comment by ahreenah** [comment]
тогда даже не так  - пусть юзеры прописывают браузер в PATH

**Comment by ahreenah** [comment]
это не помогло - проверил

**Comment by Alexey-T** [comment]
конфиг можно такой
[browsers]
MyChromeFork=c:\path\my.exe
My2=c:\my2.exe

**Comment by ahreenah** [comment]
не так
будем открывать через os.system('%s 127.0.0.1:5000/view'%(browser_name))

**Comment by ahreenah** [comment]
как получить путь до конфига?

**Comment by Alexey-T** [comment]
примеры есть. `fn_config = `

**Comment by Alexey-T** [comment]
fn_config = os.path.join(app_path(APP_DIR_SETTINGS), 'cuda_t.ini')
