### ISSUE TITLE
может сделать 3 глоб переменные- class var?

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_html_live_preview#26]
port=ini_read(fn_config,'op','port','5000')
browser_name=get_browser_name()
server_running=False

может положишь их в класс, их установку в init, а чтение - через
self.port
self.browser_name
self.running

**Comment by Alexey-T** [comment]
тогда show  тоже в класс, это будет self.show()

**Comment by ahreenah** [comment]
ни в коем случае так как сейчас плагин позволяет не перезапуская его переменить порт в конфиге и просто заново стартануть сервер
