### ISSUE TITLE
что за путь??

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_html_live_preview#4]
os.chdir('C:\\ProgramFiles\\CudaText3\\py\\cuda_html_live_preview')

**Comment by ahreenah** [comment]
fixed

**Comment by Alexey-T** [comment]
все еще есть в server.py

**Comment by ahreenah** [comment]
нет

**Comment by Alexey-T** [comment]
вот он https://github.com/medvosa/cuda_html_live_preview/blob/master/server.py#L4
