### ISSUE TITLE
Markdown bold не робит если с пробелами

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_html_live_preview#65]
лексер понимает выделение с пробелами

    test ** bold here ** ok

плагин не конвертит такое в bold. пробелы портят.
плагин Markdown Preview такое понимает. а твой нет.

**Comment by ahreenah** [comment]
Это нигде не робит кроме того плага
вот пример:
https://github.com/medvosa/cuda_html_live_preview/issues/66

**Comment by Alexey-T** [comment]
Пишу тут для теста- ** жир ** нежир

**Comment by Alexey-T** [comment]
Ты прав, скажу ему
