### ISSUE TITLE
HTML Live Preview: Does not show images

### ISSUE THREAD

**Issue by eltonfabricio10** [medvosa/cuda_html_live_preview#67]
![Captura de tela de 2021-07-11 00-44-00](https://user-images.githubusercontent.com/25956396/125182137-cb526d00-e1e1-11eb-90b5-518a82b279a8.png)

**Comment by Alexey-T** [comment]
Pictures work ok if URL is relative, seems you have an absolute picture URL?

**Comment by eltonfabricio10** [comment]
Yep, but it should work anyway.

**Comment by Alexey-T** [comment]
@halfbrained should it work anyway? seems no, the server is having its own current-folder, right?

**Comment by Alexey-T** [comment]
@eltonfabricio10 Elton, can you show original picture URLs in HTML?

**Comment by eltonfabricio10** [comment]
> @eltonfabricio10 Elton, can you show original picture URLs in HTML?

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>HTML Preview</title>
    <style type="text/css">
        body {
            background-image: url('/home/eltonff/Imagens/debian.png');
        }
    </style>
</head>
<body>
    <img src="/home/eltonff/Imagens/icon.png">
</body>
</html>
```

**Comment by halfbrained** [comment]
It should not work. Message from browser console:
``` 
Security Error: Content at http://127.0.0.1:5000/view may not load or link to file:///home/user/Downloads/html_crap/imgs/icon.png
```

So the browser prevents this on purpose
