### ISSUE TITLE
preview of Synwrite homepage not ok

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_html_live_preview#9]
берем страничку с https://github.com/alexey-t/uvviewsoft_homepage
на файле synwrite/index.htm юзаем плаг.
у меня картинок нет и css.
Firefox 66.0.5, Ubuntu 19.4

![wy](https://user-images.githubusercontent.com/4154978/57984319-505af500-7a63-11e9-9eae-491605a6125a.png)

**Comment by ahreenah** [comment]
linux?
